coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%
comment:
  layout: "reach,diff,flags,files"
  behavior: default
flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: node
      statuses:
        - type: project
          target: 100%
          threshold: 0%
        - type: patch
          target: 100%
          threshold: 0%
