sonar.projectKey=Prekzursil_pbinfo-get-unsolved
sonar.organization=prekzursil
sonar.sources=src,scripts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=dist/**,coverage/**,coverage-100/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
